---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: eapnix-dx
# description will be included in the image's metadata
description: UCEAP Linux

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    install:
      - atuin
      - awscli2
      - azure-cli
      - bat
      - btop
      - chezmoi
      - fd-find
      - gh
      - glow
      - onedrive
      - php-cli
      - php-xml
      - pv
      - ripgrep
      - neovim
      - ShellCheck
      - shfmt
      - tealdeer
      - terraform
    remove:
      - kate
      - kate-libs
      - kate-plugins
      - kate-krunner-plugin
      - kwrite

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - md.obsidian.Obsidian
        - com.google.Chrome
        - org.zealdocs.Zeal
        - io.podman_desktop.PodmanDesktop
        - io.github.getnf.embellish
        - me.iepure.devtoolbox
        - sh.loft.devpod
      remove:
        - org.kde.kontact
        - org.mozilla.Thunderbird
    user: {} # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password # install 1Password (stable) and `op` CLI tool

  - type: script
    scripts:
      - image_name.sh
      - terminus.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

